server:
  port: ${PORT:9070}
spring:
  application:
    name: oms-server
  messages:
    basename: i18n/common,i18n/user-common,i18n/permission-common
    fallback-to-system-locale: off
  web:
    locale: en_US