server:
  port: ${PORT:9000}
spring:
  application:
    name: erp-gateway

erp:
  # uri正则表达式, 多条规则, 规则之间用逗号隔开, example: '/api/user/auth/register, /api/user/auth/login/.*'
  route:
    # 不能在登录的状态下访问的路由
    un-auth: '/api/user/auth/erp/login/admin/.*'